---
abstract: "The simplest, stupidest 'pod parser' possible"
author:
  - 'Stephen R. Scaffidi <sscaffidi@cpan.org>'
build_requires:
  File::Basename: 0
  File::Slurp: 0
  Module::Build: 0.3601
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.31
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102340, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Stupid
provides:
  Pod::Stupid:
    file: lib/Pod/Stupid.pm
    version: 0.001
requires:
  Carp: 0
  Data::Dumper: 0
  English: 0
  Scalar::Util: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Pod-Stupid
  homepage: http://github.com/Hercynium/Pod-Stupid/tree
  repository: git://github.com/Hercynium/Pod-Stupid.git
version: 0.001
x_BuiltWith:
  modules:
    Carp: 1.11
    Data::Dumper: 2.126
    English: 1.04
    ExtUtils::MakeMaker: 6.56
    File::Basename: 2.77
    File::Slurp: 9999.13
    Module::Build: 0.3607
    Scalar::Util: 1.23
    Test::More: 0.96
  perl: 5.010001
  platform: linux
